from __future__ import annotations

import json
import sqlite3
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import psycopg
from psycopg.rows import dict_row


@dataclass(frozen=True)
class SavedReport:
    id: int
    user_id: int
    partner_name: str
    birth_date: str
    emotional_language_title: str
    created_at: str


DEFAULT_PROFILE: dict[str, str] = {
    "self_name": "",
    "self_birth_date": "",
    "partner_name": "",
    "partner_birth_date": "",
}


class ReportsStore:
    def __init__(self, db_path: Path, database_url: str | None = None) -> None:
        self.db_path = db_path
        self.database_url = database_url.strip() if database_url else None
        if self.database_url:
            self._init_postgres_db()
        else:
            self.db_path.parent.mkdir(parents=True, exist_ok=True)
            self._init_sqlite_db()

    def _connect_sqlite(self) -> sqlite3.Connection:
        conn = sqlite3.connect(self.db_path)
        conn.row_factory = sqlite3.Row
        return conn

    def _connect_postgres(self) -> psycopg.Connection[dict[str, Any]]:
        if not self.database_url:
            raise RuntimeError("DATABASE_URL is not configured")
        return psycopg.connect(self.database_url, row_factory=dict_row)

    def _init_sqlite_db(self) -> None:
        with self._connect_sqlite() as conn:
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS partner_reports (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    user_id INTEGER NOT NULL,
                    partner_name TEXT NOT NULL,
                    birth_date TEXT NOT NULL,
                    emotional_language TEXT NOT NULL,
                    emotional_language_title TEXT NOT NULL,
                    report_json TEXT NOT NULL,
                    created_at TEXT NOT NULL
                )
                """
            )
            conn.execute("CREATE INDEX IF NOT EXISTS idx_partner_reports_user_id ON partner_reports(user_id)")
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS bot_users (
                    user_id INTEGER PRIMARY KEY,
                    first_seen_at TEXT NOT NULL,
                    last_seen_at TEXT NOT NULL
                )
                """
            )
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS broadcast_log (
                    broadcast_key TEXT PRIMARY KEY,
                    sent_at TEXT NOT NULL,
                    total INTEGER NOT NULL,
                    success INTEGER NOT NULL,
                    failed INTEGER NOT NULL
                )
                """
            )
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS user_profiles (
                    user_id INTEGER PRIMARY KEY,
                    self_name TEXT NOT NULL DEFAULT '',
                    self_birth_date TEXT NOT NULL DEFAULT '',
                    partner_name TEXT NOT NULL DEFAULT '',
                    partner_birth_date TEXT NOT NULL DEFAULT '',
                    updated_at TEXT NOT NULL
                )
                """
            )

    def _init_postgres_db(self) -> None:
        with self._connect_postgres() as conn:
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS partner_reports (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id BIGINT NOT NULL,
                    partner_name TEXT NOT NULL,
                    birth_date TEXT NOT NULL,
                    emotional_language TEXT NOT NULL,
                    emotional_language_title TEXT NOT NULL,
                    report_json JSONB NOT NULL,
                    created_at TEXT NOT NULL
                )
                """
            )
            conn.execute("CREATE INDEX IF NOT EXISTS idx_partner_reports_user_id ON partner_reports(user_id)")
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS bot_users (
                    user_id BIGINT PRIMARY KEY,
                    first_seen_at TEXT NOT NULL,
                    last_seen_at TEXT NOT NULL
                )
                """
            )
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS broadcast_log (
                    broadcast_key TEXT PRIMARY KEY,
                    sent_at TEXT NOT NULL,
                    total INTEGER NOT NULL,
                    success INTEGER NOT NULL,
                    failed INTEGER NOT NULL
                )
                """
            )
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS user_profiles (
                    user_id BIGINT PRIMARY KEY,
                    self_name TEXT NOT NULL DEFAULT '',
                    self_birth_date TEXT NOT NULL DEFAULT '',
                    partner_name TEXT NOT NULL DEFAULT '',
                    partner_birth_date TEXT NOT NULL DEFAULT '',
                    updated_at TEXT NOT NULL
                )
                """
            )

    def register_user(self, user_id: int) -> None:
        now = datetime.now(timezone.utc).isoformat(timespec="seconds")
        if self.database_url:
            with self._connect_postgres() as conn:
                conn.execute(
                    """
                    INSERT INTO bot_users (user_id, first_seen_at, last_seen_at)
                    VALUES (%s, %s, %s)
                    ON CONFLICT(user_id) DO UPDATE SET last_seen_at = excluded.last_seen_at
                    """,
                    (user_id, now, now),
                )
            return
        with self._connect_sqlite() as conn:
            conn.execute(
                """
                INSERT INTO bot_users (user_id, first_seen_at, last_seen_at)
                VALUES (?, ?, ?)
                ON CONFLICT(user_id) DO UPDATE SET last_seen_at = excluded.last_seen_at
                """,
                (user_id, now, now),
            )

    def add(self, user_id: int, report: object) -> int:
        self.register_user(user_id)
        payload = report.to_dict()  # PartnerReport-like object. Keep storage decoupled.
        now = datetime.now(timezone.utc).isoformat(timespec="seconds")
        if self.database_url:
            with self._connect_postgres() as conn:
                cursor = conn.execute(
                    """
                    INSERT INTO partner_reports (
                        user_id, partner_name, birth_date, emotional_language,
                        emotional_language_title, report_json, created_at
                    ) VALUES (%s, %s, %s, %s, %s, %s::jsonb, %s)
                    RETURNING id
                    """,
                    (
                        user_id,
                        payload["partner_name"],
                        payload["birth_date"],
                        payload["emotional_language"],
                        payload["emotional_language_title"],
                        json.dumps(payload, ensure_ascii=False),
                        now,
                    ),
                )
                row = cursor.fetchone()
                return int(row["id"] if row else 0)
        with self._connect_sqlite() as conn:
            cursor = conn.execute(
                """
                INSERT INTO partner_reports (
                    user_id, partner_name, birth_date, emotional_language,
                    emotional_language_title, report_json, created_at
                ) VALUES (?, ?, ?, ?, ?, ?, ?)
                """,
                (
                    user_id,
                    payload["partner_name"],
                    payload["birth_date"],
                    payload["emotional_language"],
                    payload["emotional_language_title"],
                    json.dumps(payload, ensure_ascii=False),
                    now,
                ),
            )
            return int(cursor.lastrowid)

    def latest_report_payload(self, user_id: int) -> dict[str, Any] | None:
        self.register_user(user_id)
        if self.database_url:
            with self._connect_postgres() as conn:
                row = conn.execute(
                    """
                    SELECT report_json
                    FROM partner_reports
                    WHERE user_id = %s
                    ORDER BY id DESC
                    LIMIT 1
                    """,
                    (user_id,),
                ).fetchone()
        else:
            with self._connect_sqlite() as conn:
                row = conn.execute(
                    """
                    SELECT report_json
                    FROM partner_reports
                    WHERE user_id = ?
                    ORDER BY id DESC
                    LIMIT 1
                    """,
                    (user_id,),
                ).fetchone()
        if row is None:
            return None
        raw_payload = row["report_json"]
        payload = raw_payload if isinstance(raw_payload, dict) else json.loads(str(raw_payload))
        return payload if isinstance(payload, dict) else None

    def recent(self, user_id: int, limit: int = 10) -> list[SavedReport]:
        if self.database_url:
            with self._connect_postgres() as conn:
                rows = conn.execute(
                    """
                    SELECT id, user_id, partner_name, birth_date, emotional_language_title, created_at
                    FROM partner_reports
                    WHERE user_id = %s
                    ORDER BY id DESC
                    LIMIT %s
                    """,
                    (user_id, limit),
                ).fetchall()
        else:
            with self._connect_sqlite() as conn:
                rows = conn.execute(
                    """
                    SELECT id, user_id, partner_name, birth_date, emotional_language_title, created_at
                    FROM partner_reports
                    WHERE user_id = ?
                    ORDER BY id DESC
                    LIMIT ?
                    """,
                    (user_id, limit),
                ).fetchall()
        return [
            SavedReport(
                id=int(row["id"]),
                user_id=int(row["user_id"]),
                partner_name=str(row["partner_name"]),
                birth_date=str(row["birth_date"]),
                emotional_language_title=str(row["emotional_language_title"]),
                created_at=str(row["created_at"]),
            )
            for row in rows
        ]

    def all_user_ids(self) -> list[int]:
        query = """
            SELECT user_id FROM bot_users
            UNION
            SELECT DISTINCT user_id FROM partner_reports
            ORDER BY user_id
            """
        if self.database_url:
            with self._connect_postgres() as conn:
                rows = conn.execute(query).fetchall()
        else:
            with self._connect_sqlite() as conn:
                rows = conn.execute(query).fetchall()
        return [int(row["user_id"]) for row in rows]

    def was_broadcast_sent(self, broadcast_key: str) -> bool:
        if self.database_url:
            with self._connect_postgres() as conn:
                row = conn.execute(
                    "SELECT broadcast_key FROM broadcast_log WHERE broadcast_key = %s",
                    (broadcast_key,),
                ).fetchone()
        else:
            with self._connect_sqlite() as conn:
                row = conn.execute(
                    "SELECT broadcast_key FROM broadcast_log WHERE broadcast_key = ?",
                    (broadcast_key,),
                ).fetchone()
        return row is not None

    def mark_broadcast_sent(self, broadcast_key: str, total: int, success: int, failed: int) -> None:
        now = datetime.now(timezone.utc).isoformat(timespec="seconds")
        query = """
            INSERT INTO broadcast_log (broadcast_key, sent_at, total, success, failed)
            VALUES ({placeholders})
            ON CONFLICT(broadcast_key) DO UPDATE SET
                sent_at = excluded.sent_at,
                total = excluded.total,
                success = excluded.success,
                failed = excluded.failed
            """
        if self.database_url:
            with self._connect_postgres() as conn:
                conn.execute(
                    query.format(placeholders="%s, %s, %s, %s, %s"),
                    (broadcast_key, now, total, success, failed),
                )
        else:
            with self._connect_sqlite() as conn:
                conn.execute(query.format(placeholders="?, ?, ?, ?, ?"), (broadcast_key, now, total, success, failed))

    def get_profile(self, user_id: int) -> dict[str, str]:
        self.register_user(user_id)
        if self.database_url:
            with self._connect_postgres() as conn:
                row = conn.execute(
                    """
                    SELECT self_name, self_birth_date, partner_name, partner_birth_date
                    FROM user_profiles
                    WHERE user_id = %s
                    """,
                    (user_id,),
                ).fetchone()
        else:
            with self._connect_sqlite() as conn:
                row = conn.execute(
                    """
                    SELECT self_name, self_birth_date, partner_name, partner_birth_date
                    FROM user_profiles
                    WHERE user_id = ?
                    """,
                    (user_id,),
                ).fetchone()
        if row is None:
            return dict(DEFAULT_PROFILE)
        return {
            "self_name": str(row["self_name"] or ""),
            "self_birth_date": str(row["self_birth_date"] or ""),
            "partner_name": str(row["partner_name"] or ""),
            "partner_birth_date": str(row["partner_birth_date"] or ""),
        }

    def save_profile(self, user_id: int, profile: dict[str, Any]) -> dict[str, str]:
        self.register_user(user_id)
        clean = {key: str(profile.get(key, "") or "").strip()[:80] for key in DEFAULT_PROFILE}
        now = datetime.now(timezone.utc).isoformat(timespec="seconds")
        query = """
            INSERT INTO user_profiles (
                user_id, self_name, self_birth_date, partner_name, partner_birth_date, updated_at
            )
            VALUES ({placeholders})
            ON CONFLICT(user_id) DO UPDATE SET
                self_name = excluded.self_name,
                self_birth_date = excluded.self_birth_date,
                partner_name = excluded.partner_name,
                partner_birth_date = excluded.partner_birth_date,
                updated_at = excluded.updated_at
            """
        values = (
            user_id,
            clean["self_name"],
            clean["self_birth_date"],
            clean["partner_name"],
            clean["partner_birth_date"],
            now,
        )
        if self.database_url:
            with self._connect_postgres() as conn:
                conn.execute(query.format(placeholders="%s, %s, %s, %s, %s, %s"), values)
        else:
            with self._connect_sqlite() as conn:
                conn.execute(query.format(placeholders="?, ?, ?, ?, ?, ?"), values)
        return clean


def format_history(items: list[SavedReport]) -> str:
    if not items:
        return "История пока пустая. Нажми /partner и разбери первого человека. Всё великое начинается с формы ввода, как ни печально."
    lines = ["🗂 История разборов", ""]
    for item in items:
        lines.append(f"#{item.id} — {item.partner_name}, {item.birth_date}")
        lines.append(f"{item.emotional_language_title}")
        lines.append("")
    return "\n".join(lines).strip()
